### ISSUE TITLE
cs4.5 c2profile 

### ISSUE THREAD

**Issue by SD-ZZ** [boku7/BokuLoader#24]
cs4.5 c2profile use sleep_mask=true can‘t work，Whatever userwx is set to

only step instead of the normal three

![image](https://user-images.githubusercontent.com/80903238/223677588-81e9b9a0-db09-4a81-8508-1fc939583bd3.png)

![image](https://user-images.githubusercontent.com/80903238/223678176-c2f4da34-99ff-45a5-ab08-08463ac17385.png)

**Comment by boku7** [comment]
Is that the version of the CRTO lab? I only have 4.8 but if it's in CRTO I'd be able to try and check what the issue is.

Could you give me some more info?
Like what's going wrong. Is the CS script failing or are you getting an exception when running?
Is there a profile config that works and one that doesn't?

**Comment by boku7** [comment]
Just trying to get enough info to reproduce the issue myself
