### ISSUE TITLE
command not found

### ISSUE THREAD

**Issue by sec13b** [boku7/BokuLoader#30]
./Makefile: line 1: CC_x64: command not found
./Makefile: line 2: CFLAGS: command not found
./Makefile: line 2: CFLAGS: command not found
./Makefile: line 3: CFLAGS: command not found
./Makefile: line 3: CFLAGS: command not found
./Makefile: line 5: bokuloader:: command not found
./Makefile: line 6: CC_x64: command not found
./Makefile: line 6: CFLAGS: command not found
./Makefile: line 6: -c: command not found
./Makefile: line 7: clean:: command not found

**Comment by boku7** [comment]
The errors you're seeing suggest that your Makefile is being executed like a shell script rather than being processed by the `make` utility. The commands and variables in a Makefile are meant to be interpreted by `make`, not directly executed by the shell.

To correctly build the project, you should run `make` in the directory containing the Makefile, rather than trying to execute the Makefile directly:

```bash
cd /path/to/directory/with/Makefile
make
```

This way, `make` will interpret the Makefile and execute the commands as intended.
